# Definition file for AWS CodeDeploy

version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/bagisto
permissions:
  - object: /var/www/html/bagisto
    owner: ec2-user
    group: ec2-user
    type:
      - file
      - directory
hooks:
  BeforeInstall:
    - location: devops/prepare.sh
      runas: root
  AfterInstall:
    - location: devops/setup-app.sh
      runas: ec2-user


